###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:            
    db-server:
        image: mysql:8.0
        container_name: lab-app-db
        restart: unless-stopped
        environment:
          MYSQL_DATABASE: $DB_DATABASE
          MYSQL_ROOT_PASSWORD: $DB_PASSWORD_ROOT
          MYSQL_PASSWORD: $DB_PASSWORD
          MYSQL_USER: $DB_USERNAME
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        volumes:
          - ./mysql:/docker-entrypoint-initdb.d
          - dbdata:/var/lib/mysql
        ports:
          - "${DB_PORT}:3306"
        networks:
          - app-network

    webserver:
        image: 'nginx:alpine'
        container_name: lab-app-nginx
        restart: unless-stopped
        networks:
          - app-network
        working_dir: /var/www
        volumes:
            - './app:/var/www'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        depends_on:
          - app
          
    app:
        build: 
          args:
            user: sammy
            passwd: sammy**
            uid: 1000
          context: ./
          dockerfile: Dockerfile
        image: lab-app-img
        restart: unless-stopped
        container_name: lab-app-app
        networks:
          - app-network
        volumes:
          - ./app/:/var/www
          - './app/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        depends_on:
          - db-server
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
